### ISSUE TITLE
Wrong URL links at the blog pages

### ISSUE THREAD

**Issue by erkobridee** [HiDeoo/starlight-blog#102]
### Describe the bug

I'm testing the following version:
```
    ...
    "astro": "5.0.9",
    ...
    "@astrojs/starlight": "0.30.2",
    "@astrojs/starlight-tailwind": "3.0.0",
    "@astrojs/svelte": "7.0.1",
    "@astrojs/tailwind": "5.1.3",
    ...
    "starlight-blog": "0.16.0",
```

I notice that with this version, the URLs contain the file extension, in my case, `.mdx` files, which causes it to reach the 404 page instead of reaching the desired blog page

### To Reproduce

1. git clone 
```
git clone -b update/astro https://github.com/erkobridee/astro-starlight-hello.git
```
3. `npm i`
4. `npm start`
5. access the URL defined below, and you'll see that all the links rendered on the page contain the file extension (`.mdx`)
```
http://localhost:4321/en/blog
```

### Expected behavior

render the links without the file extension (`.mdx`)

### How often does this bug happen?

Every time

### System Info

- Operating System: Ubuntu 22.04.5 LTS
- Browser: Chrome
- Version: 130.0.6723.91 (Official Build) (64-bit)

**Comment by HiDeoo** [comment]
Thanks for your report.

The issue seems to be coming from a small migration mistake in https://github.com/erkobridee/astro-starlight-hello/blob/update/astro/src/content/config.ts#L9

In your `src/content/config.ts` file, the loader should be at the root of `defineCollection()` and not nested inside `docsSchema()`.

```diff
export const collections = {
  docs: defineCollection({
+   loader: docsLoader(),
    schema: docsSchema({
-     loader: docsLoader(),
      extend: (context) => blogSchema(context)
    })
  }),
  i18n: defineCollection({
    loader: i18nLoader() /*type: 'data'*/,
    schema: i18nSchema()
  })
};
```

I just tested locally and it seems to be working fine after this change.

**Comment by erkobridee** [comment]
oops, my bad

thanks a lot @HiDeoo o/

I also checked here with that change, and it's working :sweat_smile:
