### ISSUE TITLE
An error " Cannot read properties of undefined (reading 'endsWith')" occurs when i run build 

### ISSUE THREAD

**Issue by aswind7** [HiDeoo/starlight-blog#12]
### Describe the bug

error   Cannot read properties of undefined (reading 'endsWith')
  File:
    node_modules/.pnpm/starlight-blog@0.2.1_@astrojs+starlight@0.9.1_astro@3.0.8/node_modules/starlight-blog/Tags.astro
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'endsWith')

## with these pkgs of version:
"@astrojs/starlight": "^0.9.1",
    "astro": "^3.0.6",
"starlight-blog": "^0.2.1"

## run 
pnpm run build

### Expected behavior

Build Successful

### How often does this bug happen?

Every time

### System Info

macos;

**Comment by HiDeoo** [comment]
Thanks for your report. This error should have been [fixed](https://github.com/HiDeoo/starlight-blog/pull/8) in the latest version (`v0.3.2`) and it looks like you are using `v0.2.1`. 

I assume an update of the `starlight-blog` package on your end should fix it so I'm going to close this but feel free to say if it's not the case so I can re-open the issue.

**Comment by aswind7** [comment]
> Thanks for your report. This error should have been [fixed](https://github.com/HiDeoo/starlight-blog/pull/8) in the latest version (`v0.3.2`) and it looks like you are using `v0.2.1`.
> 
> I assume an update of the `starlight-blog` package on your end should fix it so I'm going to close this but feel free to say if it's not the case so I can re-open the issue.

Thanks for yours reply! I have done as you said and eventually it worked! You are so nice man, thank you again.👍
