### ISSUE TITLE
Plz add copy button and wrap column button to the code block

### ISSUE THREAD

**Issue by hapihacking** [HiDeoo/starlight-blog#15]
### Is your feature request related to a problem?

...

### Describe the solution you'd like

Can be convenient for daily use

**Comment by HiDeoo** [comment]
Thanks for your feedback.

This kind of features will be handled directly by Starlight when switching to [Expressive Code](https://github.com/expressive-code/expressive-code) which will provide a copy button, a plugin system and much more.

You can follow the latest updates regarding using Expressive Code in Starlight in this [review comment](https://github.com/withastro/starlight/pull/742#pullrequestreview-1701238653).

**Comment by hapihacking** [comment]
Thx for your answer
