### ISSUE TITLE
Co-exist with starlight documentation

### ISSUE THREAD

**Issue by brettstack** [HiDeoo/starlight-blog#16]
### Is your feature request related to a problem?

I have starlight docs page that lives at /docs on my website. I'd love to also have a /blog route that uses this package but I wasn't able to get the two to co-exist.

### Describe the solution you'd like

Do you know if it's possible or how difficult this would be to support?

**Comment by HiDeoo** [comment]
Thanks for your feedback.

Are you using something like the ["Use Starlight at a subpath"](https://starlight.astro.build/manual-setup/#use-starlight-at-a-subpath) guide (and your docs are in a `src/content/docs/docs/` directory? Or some other setup?

**Comment by brettstack** [comment]
Yes that's correct. I tried adding the blog to `src/content/docs/blog` as well as `src/content/blog/blog` and had issues with both. I didn't expect it to work since starlight-blog overrides some components so I figured it would mess with the docs.

**Comment by HiDeoo** [comment]
I setup a repro in a StackBlitz using the following steps:

1. Start from a fresh Astro installation
2. [ Add Starlight to an existing Astro site](https://starlight.astro.build/manual-setup/#set-up-starlight)
3. [Setup Starlight at a `docs` subpath](https://starlight.astro.build/manual-setup/#use-starlight-at-a-subpath)
4. Install starlight-blog

And everything worked out of the box for me. Here is the [link to the StackBlitz](https://stackblitz.com/edit/github-yshcqs?file=astro.config.mjs).

-  `/` is a classic Astro page in `src/pages/index.astro`
- `/docs` is a Starlight documentation in `src/content/docs/docs`
- `/blog` is a blog using starlight-blog in `src/content/docs/blog`

Maybe the StackBlitz can help you figure out if this is a configuration issue on your end or if you are still encountering issues, would you mind providing a repro?

**Comment by brettstack** [comment]
Thanks so much! I'll check it out and report back

**Comment by brettstack** [comment]
It worked! I think what I did before was injecting a step that wasn't necessary and broke it. Amazing! Thanks @HiDeoo

**Comment by HiDeoo** [comment]
Thanks for taking the time to check it out, really appreciate it!
