### ISSUE TITLE
Frontmatter to flag as draft/unpublished

### ISSUE THREAD

**Issue by brettstack** [HiDeoo/starlight-blog#17]
### Is your feature request related to a problem?

Hey @HiDeoo, huge fan of what you've made. It would be great if we could mark posts that aren't yet ready to be published.

### Describe the solution you'd like

One of these new frontmatter propeties:

```
draft: true
isDraft: true
published: false (default: true)
isPublished: false (default: true)
```

Then when you're ready to publish, simply remove that line.

### Describe alternatives you've considered

Alternatively, a `_drafts` directory. Then when you're ready to publish, simply drag+drop into the main folder.

**Comment by HiDeoo** [comment]
Thanks a lot 🙌 

This sounds like a great idea, makes total sense. This should also goes well with Starlight new feature to extend content collection schemas released in `v0.14.0`.

The next release main priority will be to add support for Starlight `> v0.13.1` but I think this should be fairly easy to add that too.

I'll update this issue with any progress.

**Comment by brettstack** [comment]
Hey @HiDeoo any update? 🙏

**Comment by HiDeoo** [comment]
Sorry for the delayed response.

I'm planning to address this in Starlight directly with https://github.com/withastro/starlight/discussions/990 and I'm hoping to submit a PR for this in the next few days.

**Comment by brettstack** [comment]
Thanks! "visible during development and maybe with a notice at the top like fallback content" this is perfect!

**Comment by HiDeoo** [comment]
Forgot to update this issue, but the PR is available at https://github.com/withastro/starlight/pull/1613.

Once this is released, we should be able to update the package to support this new feature.

**Comment by HiDeoo** [comment]
Version [`0.7.0`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.7.0) finally includes support for draft blog posts :tada: Thanks for your patience.

It's built on top of the equivalent Starlight feature so adding `draft: true` to a blog post frontmatter will make it a draft.

In production builds, draft blog posts are not generateed, are excluded from the blog post list and tag pages.

During development, draft blog posts are visible and a small "Draft" badge is displayed in blog post previews:

<img width="754" alt="SCR-20240502-ouic" src="https://github.com/HiDeoo/starlight-blog/assets/494699/f39ec0c0-b6df-49e4-b1d0-8c1f352c9c81">
