### ISSUE TITLE
Feature Request - Add option to disable warning

### ISSUE THREAD

**Issue by Adammatthiesen** [HiDeoo/starlight-blog#24]
### Is your feature request related to a problem?

After setting a custom ThemeSelect i get presented with the following in my log:
```
02:40:47 [WARN] [starlight-blog-plugin] It looks like you already have a `ThemeSelect` component override in your Starlight configuration.
02:40:47 [WARN] [starlight-blog-plugin] To use `starlight-blog`, remove the override for the `ThemeSelect` component.
```

### Describe the solution you'd like

I would love a toggle in the config to disable these warnings

### Describe alternatives you've considered

This does not cause any real issue, more of just a console annoyance.  for advanced use cases it would be nice to be able to disable the console warning when its intended that you are remapping the components for your setup.

**Comment by HiDeoo** [comment]
The next version of the plugin will have a slightly updated message and considering that this did not get any traction, I will close this issue for now until we have more feedback as I prefer to act on the side of caution.
