### ISSUE TITLE
Support markdown and images in All Posts page

### ISSUE THREAD

**Issue by libreom** [HiDeoo/starlight-blog#30]
### Is your feature request related to a problem?

In all posts page, plain text and no image is previewed for a blog post. In docusaurus this is not the case
Eg- https://wiki.x266.mov/blog https://codec-wiki.pages.dev/blog/
![image](https://github.com/HiDeoo/starlight-blog/assets/111110599/5c99463f-a089-4c2d-b139-6b86c0a66ed5)
![image](https://github.com/HiDeoo/starlight-blog/assets/111110599/21af2a3f-8360-44a5-adaa-781463342e01)
![image](https://github.com/HiDeoo/starlight-blog/assets/111110599/cb189b45-f343-4eac-906e-62be86a44a70)
![image](https://github.com/HiDeoo/starlight-blog/assets/111110599/6ef8fcf2-38ff-46c2-832e-d93b5aa23372)

### Describe the solution you'd like

Consider markdown and images when previewing posts

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

This should now be fixed in version [`0.6.0`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.6.0).
