### ISSUE TITLE
Feature: Allow changing the base path, currently it's set to `/blog`, I'd like to use `/news` for example!

### ISSUE THREAD

**Issue by stavros-k** [HiDeoo/starlight-blog#32]
### Is your feature request related to a problem?

It would be nice to be able to customize the url's!

### Describe the solution you'd like

The ability to change the path via the configuration

### Describe alternatives you've considered

None

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

Version [`0.6.0`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.6.0) now includes a [`prefix`](https://starlight-blog-docs.vercel.app/configuration/#prefix) option defaulting to `'blog'` that can be used to customize the base prefix for all blog routes.
