### ISSUE TITLE
i18n integration

### ISSUE THREAD

**Issue by BuckyBuck135** [HiDeoo/starlight-blog#35]
### Is your feature request related to a problem?

Summary: Currently, the `/blog` route generated by the plugin doesn't seem to be supporting an i18n project.
In my project, I have a root locale (fr), and another locale (en) in its own folder, as seen below.

```
.
├── src/
│   ├── assets/
│   ├── content/
│   │   ├── docs/
│   │   │   ├── en/
│   │   │   │   ├── blog/
│   │   │   │   │   └── first-article.md
│   │   │   │   │   └── second-article.md
│   │   │   │   └── about.mdx
│   │   │   │   └── index.mdx
│   │   │   ├── blog/
│   │   │   │   └── premier-article.md
│   │   │   │   └── deuxieme-article.md
│   │   │   └── a-propos.mdx
│   │   │   └── index.mdx
│   │   └── config.ts
│   └── env.d.ts
├── astro.config.mjs

```

However, when I try to set up a blog for the other locale (under `docs/en/blog`) I run into problems. 
* on the home page, I navigate to /blog, then hit the language switch => `/en/blog` returns 404
* on the home page, I hit the language switch to get to `/en`, then navigate to `blog` => falls back to French `/blog/`

### Describe the solution you'd like

The plug-in should accommodate an i18n setup.
Creating a `/blog` folder in the different locales folders should generate a blog homepage and link accessible via `/locale/blog/`

### Additional Context

As the plug-in documentation doesn't refer to i18n, I still tried to set up a blog for the other locale (under `docs/en/blog`), but ran into problems described above.

Thank you for your time.

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands: 

i18n support is still something on my todo list at the moment. A complete and working solution is not yet something doable without additional improvements in Starlight itself, mostly this [proposal](https://github.com/withastro/starlight/discussions/1496).

I guess the 2 choices at hand are:

- Implement a custom solution right now to at least generate the `/blog`, `/blog/X`, `/blog/tags/Y` pages in various languages by duplicating some Starlight code and having all UI strings in English in all languages.
- Wait for some progress on the i18n front in Starlight and then implement a proper solution.

Considering I'm planning to start working on some parts of the linked [proposal](https://github.com/withastro/starlight/discussions/1496) this week, I think I'll wait a bit before making a decision and get a better overview of the situation/timeline.

**Comment by BuckyBuck135** [comment]
> Considering I'm planning to start working on some parts of the linked [proposal](https://github.com/withastro/starlight/discussions/1496) this week, I think I'll wait a bit before making a decision and get a better overview of the situation/timeline.


Thank you HiDeoo,
Reading that proposal you linked and realizing this is well above my skill level, there's no much I can do to help, except for French translation when the time comes!
Looking forward to seeing how it goes.

**Comment by HiDeoo** [comment]
To give a small update: one of the last changes required to properly support i18n at the plugin level both in terms of navigation/links and also UI strings has landed in [Starlight 0.28.3](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.28.3) which was released a few hours ago.

I'll start working on implementing i18n support in this plugin in the next few days.

**Comment by cuongtqtran** [comment]
> To give a small update: one of the last changes required to properly support i18n at the plugin level both in terms of navigation/links and also UI strings has landed in [Starlight 0.28.3](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.28.3) which was released a few hours ago.
> 
> I'll start working on implementing i18n support in this plugin in the next few days.

Cannot wait for it, I'm looking forward to i18n support as well.

**Comment by HiDeoo** [comment]
Thanks for your patience everyone :raised_hands: 

It took a while to get all the pieces together to provide the i18n support I had in mind but it's finally [available](https://starlight-blog-docs.vercel.app/guides/i18n)! Not saying this would be bug-free considering the size and potential complexity of the feature but now we should be able to easily iterate on it.

**Comment by BuckyBuck135** [comment]
Looking at page.ts blows my mind away. Congrats, and thanks Hideoo!
