### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by CallMeMarcellino** [HiDeoo/starlight-blog#37]
### Is your feature request related to a problem?

I wanna be able add an RSS feed to my blogs.

### Describe the solution you'd like

For there is be a way to generate the RSS Feed for the blog.

### Describe alternatives you've considered

I'm very new to website creation, and Astro in general. I only understand RSS from a user perspective, and don't understand how it works. It seems to be a file hosted in a server, that updates every time a new blog post is posted. Hence, why, I decided to ask here if that could become a feature.

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

RSS is actually a part of my todo list for this plugin but not something I did get the time to implement yet. I'm gonna bump a bit the priority as it seems to be a feature that people are looking for (but I don't have an exact ETA yet) :thumbsup:

**Comment by HiDeoo** [comment]
I just released [`v0.8.0`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.8.0) that now includes an RSS feed for the blog 🎉 

Thanks for your patience.
