### ISSUE TITLE
Remove /blog, and make everything under /

### ISSUE THREAD

**Issue by CallMeMarcellino** [HiDeoo/starlight-blog#38]
### Is your feature request related to a problem?

My website works heavily with sub-domain, so as you can assume, my blog site is my domain with blog in front of it. The /blog that always comes after just looks werid

### Describe the solution you'd like

Maybe make it so that we can set prefix to an empty string, and if it is, then just put everything in root.

### Describe alternatives you've considered

I already tried the above solution, and it didn't work. I would also like the /blog page, which shows all the posts to be my main site, that is found when you visit the plain URL of blog.<domain>.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

> My website works heavily with sub-domain

Just to clarify, this means:

- `example.com` is your main website
- `docs.example.com` is your documentation
- `blog.example.com` should be your blog and not `docs.example.com/blog`

Is that correct?

**Comment by HiDeoo** [comment]
I see. In this case, I'm wondering if this plugin is even the proper tool. It's designed as a small Starlight companion to quickly add timestamped articles/post/news that lives alongside a Starlight documentation, e.g. `docs.example.com/blog`, `docs.example.com/changelog` or `docs.example.com/news`.

Trying to support the scenario you're describing on an entirely different domain for just this specific part feels like it would just be easier to setup something on `blog.example.com` directly vs handling domain redirection, content redirection, managing canonicals, etc.

**Comment by CallMeMarcellino** [comment]
Alright, I'll just setup smth on blog.mywebsite.com directly.

Thanks for your help!
