### ISSUE TITLE
Display images in full-text RSS feed

### ISSUE THREAD

**Issue by sarah11918** [HiDeoo/starlight-blog#45]
### Is your feature request related to a problem?

Sort of!

The RSS feed shows full-text in my feed reader (The Old Reader), but the images do not display. Instead, the alt-text is displayed.

![image](https://github.com/HiDeoo/starlight-blog/assets/5098874/04125e10-b1b7-44ec-abcd-7e0150cee66c)

### Describe the solution you'd like

I would love it if the full text of my RSS feeds displayed any included images.

### Describe alternatives you've considered

I have not tested other feed readers besides [The Old Reader](https://theoldreader.com) so I don't know how common this issue is among feed readers/client.

**Comment by HiDeoo** [comment]
[`v0.8.1`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.8.1) includes a workaround for this issue by replacing images with a placeholder and a link to the original post containing the image.

I'm keeping this issue opened as I cannot properly fix it until some upstream changes are released, specifically thinking about the [Astro Container API](https://github.com/withastro/roadmap/issues/533), and I definitely want to revisit this issue once it's possible to do so.

**Comment by scottaw66** [comment]
If you're using sanitizeHtml, make sure to tell it to include the img tag

![CleanShot 2024-05-25 at 16 09 25@2x](https://github.com/HiDeoo/starlight-blog/assets/7348442/4c5a2b99-af3d-4ff0-96a5-1e35e2821a10)
