### ISSUE TITLE
URLs do not respect `trailingSlash`

### ISSUE THREAD

**Issue by TheOtterlord** [HiDeoo/starlight-blog#48]
### Describe the bug

URLs in the sidebar & prev/next buttons don't respect `trailingSlash`, leading to an extra redirect on some hosts.

### To Reproduce

1. Go to https://starlight-blog-docs.vercel.app/blog/
2. Hover over any link in the sidebar, or the prev/next buttons

### Expected behavior

For URLs to end with `/`

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report.

I'm a bit confused about the repro as the plugin docs are not [configured](https://github.com/HiDeoo/starlight-blog/blob/main/docs/astro.config.mjs) with any `trailingSlash` option and from a quick look, sidebar links are generated using a [`getPathWithBase()`](https://github.com/HiDeoo/starlight-blog/blob/main/packages/starlight-blog/libs/page.ts#L22) function which [should respect](https://github.com/HiDeoo/starlight-blog/blob/main/packages/starlight-blog/libs/page.ts#L30) the option if specified 🤔 

Adding `trailingSlash: 'always'` to the configuration seems to also change the generated links to include a trailing slash.

**Comment by TheOtterlord** [comment]
oh yeah, replicated locally too. looks like that was missing from my repro :sweat_smile:. for content [this support thread](https://discord.com/channels/830184174198718474/1232933525049704510) is what I thought was affected. looks like it must be a different issue though.

**Comment by HiDeoo** [comment]
Thanks for linking the thread, I'll go take a look right now.
