### ISSUE TITLE
Empty RSS feed in the blog example

### ISSUE THREAD

**Issue by ematipico** [HiDeoo/starlight-blog#51]
### Describe the bug

The RSS feed is empty: https://starlight-blog-docs.vercel.app/blog/rss.xml

### To Reproduce

https://starlight-blog-docs.vercel.app/blog/rss.xml

### Expected behavior

The feeds should be populated with the content of the blog posts of https://starlight-blog-docs.vercel.app/blog/

### How often does this bug happen?

Often

**Comment by HiDeoo** [comment]
I am a bit confused about this one. Here is what I see in Chrome when visiting [`starlight-blog-docs.vercel.app/blog/rss.xml`](starlight-blog-docs.vercel.app/blog/rss.xml):

<img width="1137" alt="SCR-20240616-qsns" src="https://github.com/HiDeoo/starlight-blog/assets/494699/e9c91cd6-5b83-468a-80ea-1f317849fa08">

When `curl`ing the URL, I get the expected content length:

<img width="594" alt="SCR-20240616-qtyv" src="https://github.com/HiDeoo/starlight-blog/assets/494699/33ec8a68-7ca8-4e4e-a93a-87990832a13a">

I am not a heavy user of RSS so maybe I am doing something wrong but one potential idea I have is that the application you checked the RSS feed with may not show anything for very old entries? The demo posts are from 2020 and 2021 so maybe the application you used only shows "recent" entries?

**Comment by ematipico** [comment]
Oh, maybe a Firefox thing?

**Comment by HiDeoo** [comment]
Getting a similar result in Firefox too:

<img width="1351" alt="image" src="https://github.com/HiDeoo/starlight-blog/assets/494699/2b7278eb-104f-45ff-9f7f-15e591c8478b">

I even tried a few RSS related Firefox extensions but no luck so far.

**Comment by ematipico** [comment]
Thank you, then it's something on my machine. Thank you for the support
