### ISSUE TITLE
Have an Author profile page based off of the author config, which includes the posts they've authored

### ISSUE THREAD

**Issue by spjpgrd** [HiDeoo/starlight-blog#68]
### Is your feature request related to a problem?

Nothing big, but I'll be creating `author` profile pages for each defined author within the doc site itself, and having a the author link point to that. But this feels like it'd be nice to have out of the box!

### Describe the solution you'd like

It would be great to have these pages be auto-generated and as an option for where an author link goes to.

That way you can have a 'profile' built into the doc site itself, and being able to provide more details within the author schema so you can add as many external links as you'd like.

### Describe alternatives you've considered

Haven't done anything yet, as I've just started getting things up and running today to use this for an internal docsite.

### Additional Context

Thank you for creating so many useful plugins and integrations for Starlight!

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

Author profile pages is not something that was on my radar so far. My _very personal_ thought is that this may be a bit too much for a "small blog alongside a documentation" which is what the plugin is in the end. I think this could also be quite conflicting with the current way author links are handled as an author name would need to be a link to the author profile page. Accommodating this would require some options I assume for users to decide if they want to link to the author profile page or to the provided link for an author.

Of course, I will keep monitoring and would be happy to re-evaluate this if I get more feedback on this feature request.

**Comment by spjpgrd** [comment]
Sounds good 👍 

It would definitely add some more config options, but figured I'd bring it up since I'll probably implement this in some fashion myself and was seeing if you had any plans.

**Comment by HiDeoo** [comment]
Small update to mention that author pages are now available since the version [`0.13.0`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.13.0) of the plugin, e.g. this [one](https://starlight-blog-docs.vercel.app/blog/authors/hideoo).
