### ISSUE TITLE
Breaking change in Starlight 0.9.1

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-blog#7]
### Describe the bug

It looks like Starlight 0.9.1 introduced some changes in https://github.com/withastro/starlight/pull/647 that change the internals that this integration relies on and are now breaking builds: https://github.com/tauri-apps/tauri-docs/pull/1533

### To Reproduce

Update to Starlight 0.9.1 and attempt to build with the blog integration. 

### Expected behavior

No go boom 💥 

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
> My goodness, this is what I get for trying to do things in an airport 😅 It's the blog integration, sorry about that

Haha, no problem at all, hope you had a good flight.

This should now be fixed in the just published [version `0.3.1`](https://github.com/HiDeoo/starlight-blog/releases/tag/v0.3.1).
