### ISSUE TITLE
Howto Override Preview Component 

### ISSUE THREAD

**Issue by stephrobert** [HiDeoo/starlight-blog#84]
### Is your feature request related to a problem?

I try to override Preview component without success

### Describe the solution you'd like

I'd like add an thumbnail of the first image of the blog posts

**Comment by HiDeoo** [comment]
Thanks for the feedback.

This plugin does not have an override mechanism like Starlight. It's something I'm still considering for the future based on feedback but definitely not something short term. There are also a few considerations before implementing it, e.g. if a lot of plugins are implementing an override mechanism for their own components, it may hint that maybe it could be addressed at a higher level than just the plugin level.

A potential workaround could be to use the same approach as the one used in this [example](https://starlight-examples.netlify.app/examples/page-override/).
