### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Ranily57** [HiDeoo/starlight-blog#9]
### Is your feature request related to a problem?

It's not a real problem, just it's not the best idea to modify the source code on the node_module to change the language. 

### Describe the solution you'd like

I think about a way to get the language selected on the astro config and use it for the default text on the blog compoment.

### Describe alternatives you've considered

Creating a compoment to select the language of the blog, but it's not very optimized to have 2 language system

### Additional Context

Example of what i write:

```js
const blogSidebar = isBlog
  ? [
      {
        href: '/blog',
        isCurrent: isBlogRoot(Astro),
        label: 'All posts',
        type: 'link',
      },
      {
        entries: recentEntries.map((blogEntry) => ({
          href: `/${blogEntry.slug}`,
          isCurrent: isBlogPostPage(Astro, blogEntry.slug),
          label: blogEntry.data.title,
          type: 'link',
        })),
        label: 'Recent posts',
        type: 'group',
      },
    ]
  : []
```

with translation: 

```js
const blogSidebar = isBlog
  ? [
      {
        href: '/blog',
        isCurrent: isBlogRoot(Astro),
        label: translation.labelRoot,
        type: 'link',
      },
      {
        entries: recentEntries.map((blogEntry) => ({
          href: `/${blogEntry.slug}`,
          isCurrent: isBlogPostPage(Astro, blogEntry.slug),
          label: blogEntry.data.title,
          type: 'link',
        })),
        label: translation.labelRecent,
        type: 'group',
      },
    ]
  : []
```

And you can have a file like en.json : 

```json
{ 
"labelRoot": "All post",
"labelRecent": "Recent post"
}
```

**Comment by HiDeoo** [comment]
Thanks for the feedback.

I18n support is something that is in my todo list but it's great to have an issue to track it.

My current plan for i18n is to wait for several ongoing efforts with Starlight to be completed:

- Support for component customisation
- Plugin support

When these are done, the goal would be to transform this integration into an Starlight plugin (basically an integration that can update the Starlight configuration) so it could:

- Automatically update the Starlight configuration to provide some custom component to render the custom UI of the blog and avoid the hacky way the current UI is rendered.
- Use a plugin provided API to augment the Starlight built-in translations.

**Comment by HiDeoo** [comment]
Update: related Starlight [proposal](https://github.com/withastro/starlight/discussions/1496).
