### ISSUE TITLE
Astro 5 support

### ISSUE THREAD

**Issue by awhitford** [HiDeoo/starlight-blog#99]
### Describe the bug

When upgrading my project to Astro 5 (5.0.5) and Starlight to 0.30.0, I get the following warning:
```
 WARN  Issues with peer dependencies found
...
└─┬ starlight-blog 0.15.0
  └─┬ @astrojs/mdx 3.1.9
    └── ✕ unmet peer astro@^4.8.0: found 5.0.5
```

I suspect `@astrojs/mdx` needs to be upgraded to [4.0.2](https://www.npmjs.com/package/@astrojs/mdx).

Also the [Getting Started](https://starlight-blog-docs.vercel.app/getting-started/) steps outlined need to be [updated](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.30.0) because `src/content/config.ts` was renamed to `src/content.config.ts`.

### To Reproduce

1. Load this StackBlitz project
2. Run `pnpm install`

### Expected behavior

I do not expect to see errors or warnings.

### How often does this bug happen?

Every time

### System Info

- Mac 14.7 (23H124)
- Node v23.4.0
- pnpm 9.15.0

**Comment by HiDeoo** [comment]
Thanks for the report. I'm currently working on it and support for Starlight 0.30.0 and Astro 5 should be available in the next few days.

**Comment by pelikhan** [comment]
Thanks HiDeoo for your great work.
